settings.linksName = false;
settings.disableTree = true;
settings.disableSecondTable = true;
settings.grammName = "reqgrm-para-ger.html";
settings.grammSize = "width=650, height=600";
settings.flagsName = "reqflags-multi.html";
settings.flagsSize = "width=450, height=550";
settings.semName = "reqsem.html";
settings.mode="para_rus_ger";
settings.semSize="width=800, height=750";
settings.semHelp="help-lexic-sem.html";
language.additionalFeatures = "Дополнительные признаки и языки";
settings.flags.caption = "Доп. признаки и языки";
settings.customDraw = true;
