settings.linksName = false;
settings.disableTree = true;
settings.disableSecondTable = true;
settings.grammName = "reqgrm-para.html";
settings.grammSize = "width=650, height=550";
settings.flagsName = "reqflags-multi.html";
settings.flagsSize = "width=500, height=600";
settings.semName = false;
settings.mode="multi";
language.additionalFeatures = "Дополнительные признаки и языки";
